name: Tntshooter
version: ${project.version}
main: me.mewakin.tntshooter.Main
api-version: 1.16

commands:
  spawnwand:
    description: Spawns the fireball wand.
  tntshooter:
    usage: /command [arg(s)]